### ISSUE TITLE
Can't get ui.go_to_module to work

### ISSUE THREAD

**Issue by martini97** [meta-it/odooselenium#6]
I'm trying to run the script in  the readme and when it calls the ui.go_to_module it returns TimeoutException, but it doesn't show any messages.
I'm using Odoo 10, odooselenium 1.0.3, geckodriver 0.13.0 and selenium 3.0.2

**Comment by martini97** [comment]
`Traceback (most recent call last):
  File "odoo_selenium.py", line 17, in <module>
    ui.go_to_module('Accounting')
  File "/home/alessandrofm/Estagiario/odoo/venv/local/lib/python2.7/site-packages/odooselenium/ui.py", line 146, in go_to_module
    modules = self.list_modules()
  File "/home/alessandrofm/Estagiario/odoo/venv/local/lib/python2.7/site-packages/odooselenium/ui.py", line 134, in list_modules
    '.oe_application .oe_view_manager'
  File "/home/alessandrofm/Estagiario/odoo/venv/local/lib/python2.7/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
`

**Comment by ghost** [comment]
Hi martini97,
Actually we never use odooselenium with Odoo 10, only version 8, so I can't tell you that it's supposed to be working. As we now use Odoo 10, we'll soon test it and make it work.
BTW the master branch of odooselenium now use Chrome driver because we encounter a lot of headaches with the geckodriver wich seems pretty unstable with selenium.

**Comment by n1b0r** [comment]
@martini97 The `list_module()` search for selector $('.oe_application .oe_view_manager') which is not resolvable in odoo 10 web interface.
The web interface seems to changed a lot.
Any merge request is welcome to help support new odoo version.

@tj612 shouldn't you release specific branches for each odoo version to help community purpose MR ?

**Comment by ghost** [comment]
@n1b0r Sure, I'll create branches that match Odoo versions.
However we depend on the brain-tec web_selenium addon which isn't ported yet to Odoo 10.

**Comment by martini97** [comment]
Ok, thanks.
